#!/bin/bash
# some more ls aliases
alias sawcheck_curl_blocks='curl http://localhost:8008/blocks'
alias sawcheck_curl_peers='curl http://localhost:8008/peers'
alias sawcheck_pbft_members='sawtooth settings list --filter sawtooth.consensus.pbft.members'
alias sawcheck_poet_members='sawtooth settings list --filter sawtooth.consensus.poet.members'
alias il='intkey list'
alias ist='intkey set test 123'
alias spl='sawtooth peer list'
alias sbl='sawtooth block list'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
